name: coolmovies
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  skeleton_text:
  carousel_slider:
  get:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  graphql_flutter:
  cupertino_icons: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
flutter:
  uses-material-design: true